trigger:
  - master

pool:
  name: Default

variables:
  - name: NODE_VERSION
    value: '20.x'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test All'
        steps:
          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Install Node.js'

          # Frontend Build
          - script: |
              cd frontend
              npm ci
              npm run build
            displayName: 'Build Frontend'

          # Frontend Test
          - script: |
              cd frontend
              npm test
            displayName: 'Test Frontend'

          # Publish Frontend Artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'frontend/build'
              ArtifactName: 'frontend'
              publishLocation: 'Container'
            displayName: 'Publish Frontend Artifacts'

          # Backend Build
          - script: |
              cd backend
              npm ci
              npm run build
            displayName: 'Build Backend'

          # Backend Test
          - script: |
              cd backend
              npm test
            displayName: 'Test Backend'

          # Publish Backend Artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'backend/dist'
              ArtifactName: 'backend'
              publishLocation: 'Container'
            displayName: 'Publish Backend Artifacts'
