trigger:
  - master

pool:
  name: Default

variables:
  - name: NODE_VERSION
    value: '20.18.1' # Keep specific version for stability
  - name: NODE_PATH
    value: 'C:\Program Files\nodejs'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test All'
        steps:
          # Simplest verification possible - just using batch command directly
          - task: BatchScript@1
            inputs:
              filename: 'verify-node.cmd'
              arguments: '"$(NODE_PATH)"'
              modifyEnvironment: true
            displayName: 'Verify Node.js'
            continueOnError: true

          # Build Frontend - Direct batch file
          - task: BatchScript@1
            inputs:
              filename: 'build-frontend.cmd'
              arguments: '"$(NODE_PATH)"'
              workingFolder: '$(System.DefaultWorkingDirectory)'
            displayName: 'Build Frontend'

          # Test Frontend - Direct batch file
          - task: BatchScript@1
            inputs:
              filename: 'test-frontend.cmd'
              arguments: '"$(NODE_PATH)"'
              workingFolder: '$(System.DefaultWorkingDirectory)'
            displayName: 'Test Frontend'
          
          # Publish Frontend
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'frontend/build'
              ArtifactName: 'frontend'
              publishLocation: 'Container'
            displayName: 'Publish Frontend Artifacts'

          # Build Backend - Direct batch file
          - task: BatchScript@1
            inputs:
              filename: 'build-backend.cmd'
              arguments: '"$(NODE_PATH)"'
              workingFolder: '$(System.DefaultWorkingDirectory)'
            displayName: 'Build Backend'

          # Test Backend - Direct batch file
          - task: BatchScript@1
            inputs:
              filename: 'test-backend.cmd'
              arguments: '"$(NODE_PATH)"'
              workingFolder: '$(System.DefaultWorkingDirectory)'
            displayName: 'Test Backend'

          # Publish Backend
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'backend/dist'
              ArtifactName: 'backend'
              publishLocation: 'Container'
            displayName: 'Publish Backend Artifacts'

  # Deployment Stage using direct batch files
  - stage: Deploy
    displayName: 'Deploy'
    dependsOn: BuildAndTest
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: 'Deploy Application'
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'specific'
              itemPattern: '**'
              downloadPath: '$(System.ArtifactsDirectory)'
            displayName: 'Download Build Artifacts'

          - task: BatchScript@1
            inputs:
              filename: 'deploy.cmd'
              arguments: '"$(System.ArtifactsDirectory)" "$(Build.ArtifactStagingDirectory)"'
              workingFolder: '$(System.DefaultWorkingDirectory)'
            displayName: 'Deploy Application'
