services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    container_name: lifetrack-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3001
    # No volume mounts to avoid package.json not found errors
    depends_on:
      - backend
    restart: unless-stopped
    # Use the shell script defined in the Dockerfile
    # command: npm run dev -- --host 0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: lifetrack-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - USE_MOCK_DATABASE=true
    # No volume mounts to avoid package.json not found errors
    restart: unless-stopped
    # Use the shell script defined in the Dockerfile
    # command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health" , "||", "exit", "0"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  default:
    name: perfectltp_network
    driver: bridge 