apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  # Frontend environment variables
  {{- range $key, $value := .Values.config.frontend }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  
  # Backend environment variables
  {{- range $key, $value := .Values.config.backend }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 