apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  # Azure AD B2C authentication
  AD_CLIENT_ID: {{ .Values.secrets.adClientId | b64enc | quote }}
  AD_CLIENT_SECRET: {{ .Values.secrets.adClientSecret | b64enc | quote }}
  AD_TENANT_ID: {{ .Values.secrets.adTenantId | b64enc | quote }}
  
  # Database credentials
  COSMOS_DB_KEY: {{ .Values.secrets.cosmosDbKey | b64enc | quote }}
  
  # Azure OpenAI Service
  AZURE_OPENAI_API_KEY: {{ .Values.secrets.azureOpenaiApiKey | b64enc | quote }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.secrets.azureOpenaiEndpoint | b64enc | quote }}
  
  # Azure Storage
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.secrets.azureStorageConnectionString | b64enc | quote }} 