apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: perfectltp
    tier: backend
spec:
  selector:
    app: perfectltp
    tier: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP 