apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: perfectltp
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: perfectltp
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: perfectltp
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: perfectltp/frontend:latest  # Replace with your actual container registry and image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: perfectltp-config
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 15
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      # Use a node selector for appropriate node pool if needed
      # nodeSelector:
      #   purpose: web 